# spring.application.name=pi-ods3

# app.cors.allowed-origins=http://localhost:8081/

# mongodb
spring.data.mongodb.database=Medicalize
spring.data.mongodb.uri=mongodb+srv://infinitymusa5:RvyPcDO8GrmzwV9m@cluster0-medicalize.f748uuk.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0-Medicalize

# h2-dtb(database in memory)
# spring.datasource.url=jdbc:h2:mem:testdb
# spring.jpa.show-sql=true
# spring.h2.console.enabled=true
# spring.jpa.hibernate.ddl-auto=create-drop

# #initialization
# spring.jpa.defer-datasource-initialization=true
# spring.datasource.driverClassName=org.h2.Driver
# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# #login
# spring.datasource.username=user
# spring.datasource.password=user
